In [1]:
import pandas as pd
import seaborn as sns

In [3]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
df = df.drop(['class', 'who', 'adult_male', 'deck','embark_town','alive'], axis=1)

In [8]:
X = df.drop('survived', axis=1)
y = df['survived']

In [9]:
num_feature = ['pclass', 'age', 'sibsp', 'parch', 'fare']
cat_feature = ['sex', 'embarked', 'alone']

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [11]:
num_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [13]:
cat_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

In [15]:
processor = ColumnTransformer([
    ('num', num_transformer, num_feature),
    ('cat', cat_transformer, cat_feature)
])

In [18]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,stratify=y, random_state=42)

In [33]:
###Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

log_model = Pipeline([
    ('processor', processor),
    ('classifier', LogisticRegression(max_iter=1000))
     ])

log_model.fit(X_train,y_train)

y_pred = log_model.predict(X_test)

print('Logistic Regression Accuracy', accuracy_score(y_test,y_pred))

Logistic Regression Accuracy 0.8044692737430168

In [35]:
##Decison Tree
from sklearn.tree  import DecisionTreeClassifier
dt_model = Pipeline([
    ('processor', processor),
    ('classifier', DecisionTreeClassifier(max_depth=5, random_state=42))
])

dt_model.fit(X_train,y_train)
y_pred_dt = dt_model.predict(X_test)

print('Decsiosn Tree Accuracy', accuracy_score(y_test,y_pred_dt))

Decsiosn Tree Accuracy 0.7653631284916201

In [40]:
### Random Forest

from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline([
    ('processor', processor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print('Random Forest accuracy', accuracy_score(y_test,y_pred_rf))

Random Forest accuracy 0.7932960893854749

In [7]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True